.PHONY: clean All

All:
	@echo "----------Building project:[ DataAggr - Debug ]----------"
	@cd "DataAggr" && $(MAKE) -f  "DataAggr.mk"
clean:
	@echo "----------Cleaning project:[ DataAggr - Debug ]----------"
	@cd "DataAggr" && $(MAKE) -f  "DataAggr.mk" clean
